name: build

kind: pipeline
type: docker

volumes:
  - name: images
    host:
      path: /home/data/drone/images
  - name: bundle
    host:
      path: /home/data/drone/gems

spec_step_common: &spec_step_common
  image: abakpress/dind-testing
  pull: always
  privileged: true
  volumes:
    - name: images
      path: /images
    - name: bundle
      path: /bundle
  commands:
    - prepare-build
    - fetch-images --image abakpress/ruby-app:$RUBY_IMAGE_TAG
    - dip provision
    - dip rspec

steps:
  - name: Tests Ruby 2.2
    environment:
      COMPOSE_FILE_EXT: drone
      DOCKER_RUBY_VERSION: 2.2
      RUBY_IMAGE_TAG: 2.2-latest
      RAILS_ENV: test
    <<: *spec_step_common

  - name: Tests Ruby 2.3
    environment:
      COMPOSE_FILE_EXT: drone
      DOCKER_RUBY_VERSION: 2.3
      RUBY_IMAGE_TAG: 2.3-latest
      RAILS_ENV: test
    <<: *spec_step_common

  - name: Tests Ruby 2.4
    environment:
      COMPOSE_FILE_EXT: drone
      DOCKER_RUBY_VERSION: 2.4
      RUBY_IMAGE_TAG: 2.4-latest
      RAILS_ENV: test
    <<: *spec_step_common

  - name: release
    image: abakpress/gem-publication:latest
    pull: true
    when:
      event: push
      branch: master
      status: success
    commands:
      - release-gem
